### ISSUE TITLE
ImportError: cannot import name 'CLASSIFIEDS' from 'browser_env.env_config' 

### ISSUE THREAD

**Issue by ayudhsaxena** [kohjingyu/search-agents#1]
Running the script on the webarena dataset `run_webareana_search.sh` throws the following import error -

`ImportError: cannot import name 'CLASSIFIEDS' from 'browser_env.env_config' `

**Comment by ayudhsaxena** [comment]
@kohjingyu this modification fixes it - 

```
import os
DATASET = os.environ["DATASET"]
if DATASET == "visualwebarena":
    from browser_env.env_config import (
        CLASSIFIEDS,
        CLASSIFIEDS_RESET_TOKEN,
    )
```

    
   If you grant me access, i can raise a PR with this change

**Comment by kohjingyu** [comment]
Thanks for identifying this! If you'd like to create a PR, that'd be greatly appreciated. I think you should be able to do so without new permissions.
